# Generated by Django 4.1 on 2024-06-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Philips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inventory_no', models.CharField(max_length=255)),
                ('Location', models.CharField(max_length=255)),
                ('Owner', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('Price', models.CharField(max_length=255)),
                ('Purchase_date', models.DateTimeField(auto_now_add=True)),
                ('Active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
    ]
