# Generated by Django 4.1 on 2024-06-28 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_philips_alter_entry_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
