# Generated by Django 4.1 on 2024-06-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='David',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Owner', models.CharField(max_length=255)),
                ('Full_name', models.CharField(max_length=255)),
                ('Title', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
            ],
        ),
    ]
